# There are ton of disabling here and it may be better to disable rubocop, but I wanted to learn, so I left them in

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false  

Layout/LineLength:
  Enabled: false